development:
  adapter: postgresql
  encoding: unicode
  database: memoriae_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: memoriae_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: memoriae_production
  pool: 5
